// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdNBY6CmRoPC48BU_385fgPbFUlPYXOpk',
    appId: '1:332825725581:web:e381625659d6832316f0c4',
    messagingSenderId: '332825725581',
    projectId: 'strike-d-type',
    authDomain: 'strike-d-type.firebaseapp.com',
    storageBucket: 'strike-d-type.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxxvIvIs8PfuyhR2MhMqW7BJiIwh6us7U',
    appId: '1:332825725581:android:e4a11e2987ff45d316f0c4',
    messagingSenderId: '332825725581',
    projectId: 'strike-d-type',
    storageBucket: 'strike-d-type.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz_56FcR_O8Efbav-zjw42g03OkZKdH9U',
    appId: '1:332825725581:ios:e2f26cab494a069216f0c4',
    messagingSenderId: '332825725581',
    projectId: 'strike-d-type',
    storageBucket: 'strike-d-type.appspot.com',
    androidClientId: '332825725581-2r4k7t3deai1eh1jiq1rjur1i410tfq5.apps.googleusercontent.com',
    iosClientId: '332825725581-89l88lgiasv8efdrf936uvcdt0t3jv1k.apps.googleusercontent.com',
    iosBundleId: 'com.flutterflow.strikedtype',
  );
}
