import 'dart:math';



class GameFactory {
    //List of symbols used in the game Dobble (Spot It! in the US)
    symbols = [
      "Anchor",
      "Apple",
      "Bomb",
      "Cactus",
      "Candle",
      "Carrot",
      "Cheese",
      "Chess knight",
      "Clock",
      "Clown",
      "Diasy flower",
      "Dinosaur",
      "Dolphin",
      "Dragon",
      "Exclamation mark",
      "Eye",
      "Fire",
      "Four leaf clover",
      "Ghost",
      "Green splats",
      "Hammer",
      "Heart",
      "Ice cube",
      "Igloo",
      "Key",
      "Ladybird",
      "Light bulb",
      "Lightning bolt",
      "Lock",
      "Maple leaf",
      "Milk bottle",
      "Moon",
      "No Entry sign",
      "Orange scarecrow man",
      "Pencil",
      "Purple bird",
      "Purple cat",
      "Purple dobble sign",
      "Question Mark",
      "Red lips",
      "Scissors",
      "Skull and crossbones",
      "Snowflake",
      "Snowman",
      "Spider",
      "Spider’s web",
      "Sun",
      "Sunglasses",
      "Target",
      "Taxi",
      "Tortoise",
      "Treble clef",
      "Tree",
      "Water drop",
      "Dog",
      "Yin and Yang",
      "Zebra"
    ];
  }